; ESP32-C3 SuperMini + MAX-M10S (UART GPS)
[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1

board_build.flash_mode = dio

lib_deps =
	mikalhart/TinyGPSPlus@^1.0.3
